package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

const exampleInput = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

func TestExample(t *testing.T) {
	s, err := part1([]byte(exampleInput))
	assert.NoError(t, err)
	assert.Equal(t, 21, s)
}
